# Generated by Django 4.2.11 on 2024-04-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_pricing_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='gerneral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricing',
            name='school_corporate',
            field=models.BooleanField(default=False),
        ),
    ]
