# Generated by Django 4.2.11 on 2024-04-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('coach', models.CharField(max_length=100)),
                ('captain', models.CharField(max_length=100)),
                ('team_logo', models.IntegerField()),
            ],
        ),
    ]
