# Generated by Django 4.2.11 on 2024-04-11 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_footballteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballteam',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Authentication.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.CreateModel(
            name='PlayerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('no_goals', models.BigIntegerField()),
                ('no_matches', models.BigIntegerField()),
                ('football_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.footballteam')),
            ],
        ),
    ]
